### ISSUE TITLE
send_msg encoding should be UTF-8 not platform default

### ISSUE THREAD

**Issue by kspar** [kspar/jsocket#1]

**Comment by kspar** [comment]
Workaround:

instead of `jsock.send_msg(src);`
use `jsock.send(src.getBytes("UTF-8"));`

**Comment by czifro** [comment]
This issue caught my attention. I have addressed this in commits: 51fa7ac and 267fafd of the original repo. If you merge this fix into your fork, this workaround won't be necessary.

Feel free to post issues on the original repo or submit PR. Thanks for using my lib!

**Comment by kspar** [comment]
Thanks!
